apiVersion: v1
kind: Secret
metadata:
  name: mongodb-credentials
  namespace: {{ .Values.namespace.name }}
  labels:
    app: {{ .Values.app.name }}
    app.kubernetes.io/name: {{ .Values.app.name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  MONGODB_USERNAME: {{ .Values.mongodb.username | quote }}
  MONGODB_PASSWORD: {{ .Values.mongodb.password | quote }}
  MONGODB_DATABASE: {{ .Values.mongodb.database | quote }}
