#cloud-config
# Cloud-init configuration for MongoDB VM
# This sets up an OUTDATED Linux version with MongoDB

# Use Ubuntu 18.04 LTS (outdated - released in 2018, EOL April 2023)
# Current LTS is 22.04/24.04, so this is 1+ years outdated

package_update: true
package_upgrade: false  # Don't upgrade to keep system outdated

packages:
  - wget
  - curl
  - gnupg
  - ufw

users:
  - name: mongodb-admin
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC... # Add your SSH public key here

# Overly permissive CSP permissions (simulated via IAM role)
# In actual deployment, attach IAM role with permissions like:
# - ec2:RunInstances
# - ec2:CreateSecurityGroup
# - ec2:AuthorizeSecurityGroupIngress
# - iam:CreateRole
# - iam:AttachRolePolicy

runcmd:
  # Install MongoDB 4.4.18 (OUTDATED)
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.4.asc | apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/4.4 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.4.list
  - apt-get update
  - DEBIAN_FRONTEND=noninteractive apt-get install -y mongodb-org=4.4.18 mongodb-org-server=4.4.18 mongodb-org-shell=4.4.18
  
  # Configure MongoDB (INSECURE - bind to all interfaces)
  - |
    cat > /etc/mongod.conf << 'EOF'
    net:
      port: 27017
      bindIp: 0.0.0.0
    storage:
      dbPath: /var/lib/mongodb
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
    EOF
  
  # Start MongoDB
  - systemctl start mongod
  - systemctl enable mongod
  
  # Enable SSH password authentication (INSECURE)
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
  
  # Set weak root password (INSECURE)
  - echo "root:Password123" | chpasswd

write_files:
  - path: /etc/motd
    content: |
      ================================================
      MongoDB Database Server - OUTDATED CONFIGURATION
      ================================================
      
      WARNING: This VM is intentionally misconfigured
      for security testing purposes.
      
      - Ubuntu 18.04 LTS (OUTDATED)
      - MongoDB 4.4.18 (OUTDATED)
      - SSH exposed to internet
      - Overly permissive IAM permissions
      
      ================================================

final_message: "MongoDB VM setup complete after $UPTIME seconds"
