#cloud-config
# Cloud-init configuration for MongoDB VM
# This sets up an OUTDATED Linux version with MongoDB

# Use Ubuntu 18.04 LTS (outdated - released in 2018, EOL April 2023)
# Current LTS is 22.04/24.04, so this is 1+ years outdated

package_update: true
package_upgrade: false  # Don't upgrade to keep system outdated

packages:
  - wget
  - curl
  - gnupg
  - ufw
  - awscli

# Use default ubuntu user (EC2 key pair will be automatically added by AWS)

# Overly permissive CSP permissions (simulated via IAM role)
# In actual deployment, attach IAM role with permissions like:
# - ec2:RunInstances
# - ec2:CreateSecurityGroup
# - ec2:AuthorizeSecurityGroupIngress
# - iam:CreateRole
# - iam:AttachRolePolicy

runcmd:
  # Install MongoDB 4.0.28 (OUTDATED - compatible with Ubuntu 18.04)
  - wget -qO - https://www.mongodb.org/static/pgp/server-4.0.asc | apt-key add -
  - wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | apt-key add -
  - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.0 multiverse" | tee /etc/apt/sources.list.d/mongodb-org-4.0.list
  - apt-get update --allow-insecure-repositories
  - DEBIAN_FRONTEND=noninteractive apt-get install -y --allow-unauthenticated mongodb-org=4.0.28 mongodb-org-server=4.0.28 mongodb-org-shell=4.0.28
  
  # Configure MongoDB (INSECURE - bind to all interfaces)
  - |
    cat > /etc/mongod.conf << 'EOF'
    net:
      port: 27017
      bindIp: 0.0.0.0
    storage:
      dbPath: /var/lib/mongodb
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
    EOF
  
  # Start MongoDB
  - systemctl start mongod
  - systemctl enable mongod
  
  # Setup MongoDB backups to S3
  - |
    cat > /usr/local/bin/backup-mongodb.sh << 'BACKUP_SCRIPT'
    #!/bin/bash
    set -e
    BACKUP_DIR="/var/backups/mongodb"
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_NAME="mongodb_backup_${TIMESTAMP}"
    S3_BUCKET="mongodb-backups-wiz-512231857943"
    S3_REGION="us-east-1"
    
    mkdir -p ${BACKUP_DIR}
    mongodump --out="${BACKUP_DIR}/${BACKUP_NAME}" --gzip
    cd ${BACKUP_DIR}
    tar -czf "${BACKUP_NAME}.tar.gz" "${BACKUP_NAME}"
    rm -rf "${BACKUP_NAME}"
    
    aws s3 cp "${BACKUP_DIR}/${BACKUP_NAME}.tar.gz" "s3://${S3_BUCKET}/${BACKUP_NAME}.tar.gz" --region ${S3_REGION}
    
    find ${BACKUP_DIR} -name "mongodb_backup_*.tar.gz" -mtime +7 -delete
    echo "Backup completed: ${BACKUP_NAME}.tar.gz"
    BACKUP_SCRIPT
  - chmod +x /usr/local/bin/backup-mongodb.sh
  - echo "*/5 * * * * /usr/local/bin/backup-mongodb.sh >> /var/log/mongodb-backup.log 2>&1" | crontab -
  - touch /var/log/mongodb-backup.log
  - chmod 644 /var/log/mongodb-backup.log
  
  # Enable SSH password authentication (INSECURE)
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
  
  # Set weak root password (INSECURE)
  - echo "root:Password123" | chpasswd

write_files:
  - path: /etc/motd
    content: |
      ================================================
      MongoDB Database Server - OUTDATED CONFIGURATION
      ================================================
      
      WARNING: This VM is intentionally misconfigured
      for security testing purposes.
      
      - Ubuntu 18.04 LTS (OUTDATED)
      - MongoDB 4.4.18 (OUTDATED)
      - SSH exposed to internet
      - Overly permissive IAM permissions
      
      ================================================

final_message: "MongoDB VM setup complete after $UPTIME seconds"
