apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: todo-app-admin-binding
  labels:
    app: todo-app
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin  # INSECURE: Grants full cluster admin privileges
subjects:
- kind: ServiceAccount
  name: todo-app-admin
  namespace: todo-app

---
# WARNING: This configuration is INTENTIONALLY INSECURE
# The todo-app pods have cluster-admin privileges, allowing them to:
# - Create, modify, and delete any resource in any namespace
# - Read secrets from any namespace
# - Modify RBAC policies
# - Create new service accounts with elevated privileges
# - Access the Kubernetes API with full administrative rights
#
# This is a severe security misconfiguration that should NEVER be used in production.
# It is implemented here solely for the Wiz Technical Exercise demonstration purposes.
